
all: clean client server

client:
        gcc -Wno-int-to-pointer-cast -Wno-implicit-function-declaration -o clie$

server:
        gcc -pthread -Wno-sizeof-array-argument -Wno-int-conversion -Wno-int-to$

.PHONY: clean

clean:
        rm -f client
        rm -f server
